<a href="https://colab.research.google.com/github/ajayvarande20/Development-of-Interactive-Cyber-Threat-Visualization-Dashboard/blob/master/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Object-Oriented Programming (OOP) in Python

Object-Oriented Programming (OOP) is a programming paradigm that organizes software design around data, or objects, rather than functions and logic. It aims to implement real-world entities like inheritance, hiding, polymorphism, etc., in programming.

Python is a multi-paradigm language and fully supports OOP.

### Core Concepts of OOP:

1.  **Class**: A blueprint or a template for creating objects. It defines a set of attributes (data) and methods (functions) that the objects created from the class will have.
2.  **Object**: An instance of a class. It's a concrete entity created from a class.
3.  **Attributes**: Variables that belong to an object. They represent the state or characteristics of an object.
4.  **Methods**: Functions that belong to an object. They represent the behavior or actions that an object can perform.
5.  **Encapsulation**: The bundling of data (attributes) and methods that operate on the data into a single unit (class). It restricts direct access to some of an object's components, which can prevent accidental modification of data. In Python, encapsulation is achieved through naming conventions (e.g., `_attribute` for protected, `__attribute` for private).
6.  **Inheritance**: A mechanism that allows a new class (subclass/derived class) to inherit attributes and methods from an existing class (superclass/base class). This promotes code reusability and establishes a 'is-a' relationship.
7.  **Polymorphism**: The ability of an object to take on many forms. In OOP, it allows objects of different classes to be treated as objects of a common superclass. In Python, this is often achieved through method overriding and duck typing.
8.  **Abstraction**: The process of hiding the complex implementation details and showing only the essential features of an object. In Python, abstract classes and methods (using the `abc` module) are used to achieve abstraction.

### 1. Classes and Objects

-   **Class**: A user-defined blueprint or prototype from which objects are created. Classes provide a means of bundling data and functionality together.
-   **Object**: An instance of a class. When a class is defined, no memory is allocated until an object of that class is created.

In [9]:
class Dog:
    # Class attribute
    species = "Canis familiaris"

    # Constructor method (initializer)
    def __init__(self, name, age):
        self.name = name  # Instance attribute
        self.age = age    # Instance attribute

    # Instance method
    def bark(self):
        return f"{self.name} says Woof!"

    # Another instance method
    def description(self):
        return f"{self.name} is {self.age} years old."


# Creating objects (instances of the Dog class)
my_dog = Dog("Buddy", 5)
your_dog = Dog("Lucy", 3)

# Accessing attributes
print(f"My dog's name: {my_dog.name}")
print(f"My dog's age: {my_dog.age}")
print(f"My dog's species: {my_dog.species}")

print(f"\nYour dog's name: {your_dog.name}")
print(f"Your dog's age: {your_dog.age}")

# Calling methods
print(f"\n{my_dog.bark()}")
print(f"{your_dog.description()}")

# Class attribute accessed via class name
print(f"\nDog species: {Dog.species}")

My dog's name: Buddy
My dog's age: 5
My dog's species: Canis familiaris

Your dog's name: Lucy
Your dog's age: 3

Buddy says Woof!
Lucy is 3 years old.

Dog species: Canis familiaris


### 2. Attributes and Methods

-   **Attributes**: Data associated with a class or an object.
    -   **Class Attributes**: Belong to the class itself, shared by all instances of the class.
    -   **Instance Attributes**: Unique to each instance of the class, defined within the `__init__` method.
-   **Methods**: Functions defined inside a class that operate on the objects of that class.
    -   **Instance Methods**: Operate on instance attributes and require an instance of the class to be called. They take `self` as the first parameter.
    -   **Class Methods**: Operate on class attributes and take `cls` (conventionally) as the first parameter, referring to the class itself. They are defined using the `@classmethod` decorator.
    -   **Static Methods**: Do not operate on either instance or class attributes. They are essentially regular functions logically grouped with a class. They don't take `self` or `cls` and are defined using the `@staticmethod` decorator.

In [10]:
class Car:
    # Class attribute
    wheels = 4

    def __init__(self, make, model, year):
        self.make = make      # Instance attribute
        self.model = model    # Instance attribute
        self.year = year      # Instance attribute
        self.speed = 0        # Another instance attribute

    # Instance method
    def accelerate(self, increment):
        self.speed += increment
        return f"The {self.make} {self.model} is now at {self.speed} km/h."

    # Instance method
    def get_info(self):
        return f"A {self.year} {self.make} {self.model} with {self.wheels} wheels."

    @classmethod
    def change_wheels(cls, new_wheels):
        cls.wheels = new_wheels
        print(f"All cars now have {cls.wheels} wheels.")

    @staticmethod
    def honk():
        return "Beep beep!"

# Create a car object
my_car = Car("Toyota", "Corolla", 2020)

print(my_car.get_info()) # Calling instance method
print(my_car.accelerate(50)) # Calling instance method
print(my_car.speed)
print(Car.honk()) # Calling static method via class
print(my_car.honk()) # Calling static method via instance

# Accessing class attribute
print(f"Initial number of wheels: {Car.wheels}")

# Using class method to change class attribute
Car.change_wheels(6)

# Verify that the class attribute has changed for all instances
print(f"New number of wheels (via class): {Car.wheels}")
new_car = Car("Ford", "Mustang", 2023)
print(f"New car also has {new_car.wheels} wheels.")

A 2020 Toyota Corolla with 4 wheels.
The Toyota Corolla is now at 50 km/h.
50
Beep beep!
Beep beep!
Initial number of wheels: 4
All cars now have 6 wheels.
New number of wheels (via class): 6
New car also has 6 wheels.


### 3. Encapsulation

Encapsulation involves bundling data (attributes) and methods that operate on the data within a single unit (a class) and restricting direct access to some of an object's components. This protects the data from external interference and misuse.

In Python, there's no strict `private` keyword like in Java or C++. Encapsulation is achieved by convention:

-   **Public**: Attributes/methods with no leading underscore. Accessible from anywhere.
-   **Protected**: Attributes/methods starting with a single underscore (e.g., `_protected_attribute`). This is a convention indicating that it should not be accessed directly from outside the class, but it's not strictly enforced.
-   **Private**: Attributes/methods starting with double underscores (e.g., `__private_attribute`). Python's name mangling makes it harder (but not impossible) to access them directly from outside the class, changing their name to `_ClassName__private_attribute`.

In [11]:
class BankAccount:
    def __init__(self, owner, initial_balance):
        self.owner = owner  # Public attribute
        self._account_number = "123456789" # Protected attribute (by convention)
        self.__balance = initial_balance # Private attribute (name mangled)

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited ${amount}. New balance: ${self.__balance}")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.__balance}")
        else:
            print("Invalid withdrawal amount or insufficient funds.")

    def get_balance(self):
        return self.__balance

# Create an account
account = BankAccount("Alice", 1000)

# Accessing public attribute
print(f"Account owner: {account.owner}")

# Attempting to access protected attribute (discouraged but possible)
print(f"Account number (protected): {account._account_number}")

# Attempting to access private attribute directly (will cause AttributeError)
try:
    print(f"Balance (private): {account.__balance}")
except AttributeError as e:
    print(f"Error accessing __balance directly: {e}")

# Accessing private attribute via a public method
print(f"Balance (via method): ${account.get_balance()}")

# Using methods to modify balance
account.deposit(500)
account.withdraw(200)
account.withdraw(2000) # Insufficient funds

# Accessing name-mangled private attribute (not recommended for direct use)
print(f"Balance via name mangling: ${account._BankAccount__balance}")

Account owner: Alice
Account number (protected): 123456789
Error accessing __balance directly: 'BankAccount' object has no attribute '__balance'
Balance (via method): $1000
Deposited $500. New balance: $1500
Withdrew $200. New balance: $1300
Invalid withdrawal amount or insufficient funds.
Balance via name mangling: $1300


### 4. Inheritance

Inheritance allows a class (subclass/derived class) to inherit properties (attributes and methods) from another class (superclass/base class). This promotes code reusability and establishes a hierarchical relationship (Is-A relationship).

-   **Single Inheritance**: A class inherits from a single base class.
-   **Multiple Inheritance**: A class inherits from multiple base classes.
-   **Method Overriding**: A subclass can provide its own implementation of a method that is already defined in its superclass.
-   **`super()` function**: Used to call methods from a parent class within a child class.

In [12]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        raise NotImplementedError("Subclass must implement abstract method")

    def eat(self):
        return f"{self.name} is eating."

class Dog(Animal):  # Dog inherits from Animal
    def __init__(self, name, breed):
        super().__init__(name)  # Call parent class's constructor
        self.breed = breed

    # Override the speak method
    def speak(self):
        return f"{self.name} the {self.breed} barks."

class Cat(Animal):  # Cat inherits from Animal
    def __init__(self, name, color):
        super().__init__(name)
        self.color = color

    # Override the speak method
    def speak(self):
        return f"{self.name} the {self.color} cat meows."

class WorkingDog(Dog): # Multi-level inheritance
    def __init__(self, name, breed, task):
        super().__init__(name, breed)
        self.task = task

    def perform_task(self):
        return f"{self.name} is performing its task: {self.task}."

# Create objects of derived classes
dog = Dog("Buddy", "Golden Retriever")
cat = Cat("Whiskers", "Tabby")
working_dog = WorkingDog("Rex", "German Shepherd", "herding sheep")

print(dog.eat()) # Inherited method
print(dog.speak()) # Overridden method

print(cat.eat()) # Inherited method
print(cat.speak()) # Overridden method

print(working_dog.speak()) # Inherited and overridden method from Dog
print(working_dog.perform_task()) # New method in WorkingDog

Buddy is eating.
Buddy the Golden Retriever barks.
Whiskers is eating.
Whiskers the Tabby cat meows.
Rex the German Shepherd barks.
Rex is performing its task: herding sheep.


### 5. Polymorphism

Polymorphism means 'many forms'. In OOP, it refers to the ability of an object to take on many forms or the ability of different classes to respond to the same method call in their own specific ways. This allows you to write generic code that can work with objects of different types.

Python achieves polymorphism primarily through:

-   **Method Overriding**: As seen in inheritance, a subclass can redefine a method from its superclass.
-   **Duck Typing**: If it walks like a duck and quacks like a duck, then it must be a duck. In Python, the type of an object is less important than the methods it defines. If an object has the necessary methods, it can be used, regardless of its explicit type.

In [13]:
class Bird:
    def fly(self):
        return "Bird is flying."

class Airplane:
    def fly(self):
        return "Airplane is flying."

class Superman:
    def fly(self):
        return "Superman is flying."

# A function that can take any object that has a 'fly' method
def make_it_fly(entity):
    print(entity.fly())

# Objects of different classes
bird = Bird()
airplane = Airplane()
superman = Superman()

# Demonstrate polymorphism using the make_it_fly function
make_it_fly(bird)
make_it_fly(airplane)
make_it_fly(superman)

# Example with method overriding (from the inheritance example):
animals = [Dog("Max", "Labrador"), Cat("Phoebe", "Siamese")]

for animal in animals:
    print(animal.speak()) # Each object responds to 'speak' in its own way

Bird is flying.
Airplane is flying.
Superman is flying.
Max the Labrador barks.
Phoebe the Siamese cat meows.


### 6. Abstraction

Abstraction is the process of hiding the internal implementation details and showing only the essential features of an object to the outside world. It helps in managing complexity by providing a simpler, high-level view.

In Python, abstraction can be achieved using **Abstract Base Classes (ABCs)** from the `abc` module. An abstract class cannot be instantiated, and its abstract methods must be implemented by its concrete subclasses.



In [14]:
from abc import ABC, abstractmethod

class Shape(ABC): # Declare Shape as an Abstract Base Class
    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def perimeter(self):
        pass

    def description(self):
        return "This is a shape."

class Circle(Shape): # Circle inherits from Shape
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14159 * self.radius * self.radius

    def perimeter(self):
        return 2 * 3.14159 * self.radius

class Rectangle(Shape): # Rectangle inherits from Shape
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

# You cannot instantiate an abstract class
try:
    abstract_shape = Shape()
except TypeError as e:
    print(f"Error trying to instantiate Shape: {e}")

# Create concrete objects
circle = Circle(5)
rectangle = Rectangle(4, 6)

print(f"Circle area: {circle.area()}")
print(f"Circle perimeter: {circle.perimeter()}")
print(circle.description()) # Inherited concrete method

print(f"\nRectangle area: {rectangle.area()}")
print(f"Rectangle perimeter: {rectangle.perimeter()}")

Error trying to instantiate Shape: Can't instantiate abstract class Shape without an implementation for abstract methods 'area', 'perimeter'
Circle area: 78.53975
Circle perimeter: 31.4159
This is a shape.

Rectangle area: 24
Rectangle perimeter: 20


## Python Data Types

In programming, data types are classifications that tell the interpreter how the programmer intends to use the data. Python, being a dynamically typed language, automatically infers the data type based on the value assigned to a variable. However, it's crucial to understand these types to effectively manipulate data.

Python's built-in data types can be broadly categorized as follows:

1.  **Numeric Types**: `int`, `float`, `complex`
2.  **Sequence Types**: `str`, `list`, `tuple`, `range`
3.  **Mapping Type**: `dict`
4.  **Set Types**: `set`, `frozenset`
5.  **Boolean Type**: `bool`
6.  **None Type**: `NoneType` (represented by `None`)
7.  **Binary Types**: `bytes`, `bytearray`, `memoryview` (less common for beginners)

Let's explore each category with examples.

### 1. Numeric Types

These represent numerical values. Python supports three distinct numeric types:

-   **`int` (Integers)**: Whole numbers, positive or negative, without a decimal point. Python integers have arbitrary precision, meaning they can be as large as your memory allows.
-   **`float` (Floating-point numbers)**: Numbers with a decimal point or an exponent. They represent real numbers.
-   **`complex` (Complex numbers)**: Numbers with a real and an imaginary part, written as `x + yj`.

In [15]:
# Integers
my_int = 100
print(f"Type of {my_int}: {type(my_int)}")

# Floating-point numbers
my_float = 3.14
print(f"Type of {my_float}: {type(my_float)}")
my_scientific_float = 1.23e-5 # 0.0000123
print(f"Type of {my_scientific_float}: {type(my_scientific_float)}")

# Complex numbers
my_complex = 3 + 4j
print(f"Type of {my_complex}: {type(my_complex)}")

Type of 100: <class 'int'>
Type of 3.14: <class 'float'>
Type of 1.23e-05: <class 'float'>
Type of (3+4j): <class 'complex'>


### 2. Sequence Types

Sequences are ordered collections of items. They allow you to store multiple values in an organized way. Python has several built-in sequence types:

-   **`str` (Strings)**: Immutable sequences of Unicode characters, used to represent text.
-   **`list` (Lists)**: Mutable, ordered sequences of items. Items can be of different data types. Lists are defined using square brackets `[]`.
-   **`tuple` (Tuples)**: Immutable, ordered sequences of items. Similar to lists but cannot be changed after creation. Tuples are defined using parentheses `()`.
-   **`range` (Ranges)**: Immutable sequences of numbers, often used for looping a specific number of times. It's a memory-efficient way to represent sequences of integers.

In [16]:
# Strings
my_string = "Hello, Python!"
print(f"Type of '{my_string}': {type(my_string)}")
print(f"First character: {my_string[0]}")

# Lists (mutable)
my_list = [1, 'apple', 3.14, True]
print(f"Type of {my_list}: {type(my_list)}")
print(f"Second item: {my_list[1]}")
my_list[0] = 10 # Lists can be changed
print(f"Modified list: {my_list}")

# Tuples (immutable)
my_tuple = (1, 'banana', 2.71, False)
print(f"Type of {my_tuple}: {type(my_tuple)}")
print(f"Third item: {my_tuple[2]}")
# my_tuple[0] = 10 # This would raise a TypeError

# Range
my_range = range(5) # Represents numbers from 0 to 4
print(f"Type of {my_range}: {type(my_range)}")
print(f"Numbers in range: {list(my_range)}")

Type of 'Hello, Python!': <class 'str'>
First character: H
Type of [1, 'apple', 3.14, True]: <class 'list'>
Second item: apple
Modified list: [10, 'apple', 3.14, True]
Type of (1, 'banana', 2.71, False): <class 'tuple'>
Third item: 2.71
Type of range(0, 5): <class 'range'>
Numbers in range: [0, 1, 2, 3, 4]


### 3. Mapping Type

-   **`dict` (Dictionaries)**: Mutable, unordered collections of key-value pairs. Each key must be unique and immutable, while values can be of any data type and can be duplicated. Dictionaries are defined using curly braces `{}`.

In [17]:
my_dict = {"name": "Alice", "age": 30, "city": "New York"}
print(f"Type of {my_dict}: {type(my_dict)}")
print(f"Alice's age: {my_dict['age']}")
my_dict['age'] = 31 # Dictionaries are mutable
print(f"Updated dictionary: {my_dict}")

Type of {'name': 'Alice', 'age': 30, 'city': 'New York'}: <class 'dict'>
Alice's age: 30
Updated dictionary: {'name': 'Alice', 'age': 31, 'city': 'New York'}


### 4. Set Types

Sets are unordered collections of unique elements. They are useful for mathematical set operations like union, intersection, and difference.

-   **`set`**: Mutable, unordered collection of unique hashable items.
-   **`frozenset`**: Immutable version of a set. Useful when you need a set to be an element of another set, or as a dictionary key.

In [18]:
# Sets (mutable)
my_set = {1, 2, 3, 2, 1} # Duplicate elements are automatically removed
print(f"Type of {my_set}: {type(my_set)}")
print(f"Set elements: {my_set}")
my_set.add(4)
print(f"Modified set: {my_set}")

# Frozensets (immutable)
my_frozenset = frozenset([1, 2, 3])
print(f"Type of {my_frozenset}: {type(my_frozenset)}")
# my_frozenset.add(4) # This would raise an AttributeError

Type of {1, 2, 3}: <class 'set'>
Set elements: {1, 2, 3}
Modified set: {1, 2, 3, 4}
Type of frozenset({1, 2, 3}): <class 'frozenset'>


### 5. Boolean Type

-   **`bool` (Booleans)**: Represents truth values. It can only be `True` or `False`. Often used in conditional statements and loops.

In [19]:
is_active = True
print(f"Type of {is_active}: {type(is_active)}")

is_greater = (10 > 5)
print(f"Is 10 greater than 5? {is_greater}")

is_equal = (10 == 5)
print(f"Is 10 equal to 5? {is_equal}")

Type of True: <class 'bool'>
Is 10 greater than 5? True
Is 10 equal to 5? False


### 6. None Type

-   **`NoneType`**: Represents the absence of a value or a null value. It's often used to signify that a variable has not been assigned a value or a function doesn't return anything explicitly.

In [20]:
my_variable = None
print(f"Type of {my_variable}: {type(my_variable)}")

def do_nothing():
    pass # This function implicitly returns None

result = do_nothing()
print(f"Result of do_nothing(): {result}")

Type of None: <class 'NoneType'>
Result of do_nothing(): None


### Key Takeaways:

-   **Mutable vs. Immutable**: Some data types can be changed after creation (mutable), while others cannot (immutable).
    -   **Mutable**: `list`, `dict`, `set`, `bytearray`
    -   **Immutable**: `int`, `float`, `complex`, `str`, `tuple`, `frozenset`, `bytes`
-   **Dynamic Typing**: Python handles data types automatically, so you don't need to declare them explicitly.
-   **`type()` function**: Use the built-in `type()` function to check the data type of any variable or value.

## Pandas Library in Python

**Pandas** is a fast, powerful, flexible, and easy-to-use open-source data analysis and manipulation tool, built on top of the Python programming language.

It is particularly well-suited for working with **tabular data**, similar to data found in spreadsheets (like Excel) or SQL tables. Its two primary data structures are:

1.  **`Series`**: A one-dimensional labeled array capable of holding any data type.
2.  **`DataFrame`**: A two-dimensional labeled data structure with columns of potentially different types. You can think of it as a spreadsheet, a SQL table, or a dictionary of Series objects.

### Key Features of Pandas:

*   **Data Alignment**: Handles missing data by aligning data from different sources based on labels.
*   **Flexible Indexing**: Allows for easy labeling and access to data.
*   **Rich Functionality**: Provides tools for reading/writing data to various formats (CSV, Excel, SQL databases, HDF5), data cleaning, manipulation, merging, reshaping, and aggregation.
*   **Time Series Functionality**: Robust tools for working with time-series data.
*   **High Performance**: Optimized for performance, largely due to its underlying implementation in C and NumPy.

In [21]:
import pandas as pd

print("Pandas library imported successfully!")

Pandas library imported successfully!


### Creating a DataFrame

Let's create a simple DataFrame from a dictionary.

In [22]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Occupation': ['Engineer', 'Artist', 'Doctor', 'Manager']
}

df = pd.DataFrame(data)
display(df)

Name  Age         City Occupation
0    Alice   25     New York   Engineer
1      Bob   30  Los Angeles     Artist
2  Charlie   35      Chicago     Doctor
3    David   40      Houston    Manager

### Basic DataFrame Operations

*   **Viewing Data**: `.head()`, `.tail()`, `.info()`, `.describe()`
*   **Selecting Columns**: `df['ColumnName']` or `df[['Col1', 'Col2']]`
*   **Filtering Rows**: `df[df['Column'] > value]`
*   **Adding New Columns**

In [23]:
# Display the first 2 rows
print("\nFirst 2 rows:")
display(df.head(2))

# Get a summary of the DataFrame
print("\nDataFrame Info:")
df.info()

# Get descriptive statistics for numerical columns
print("\nDescriptive Statistics:")
display(df.describe())

# Select a single column (returns a Series)
print("\n'Name' column (Series):")
display(df['Name'])

# Select multiple columns (returns a DataFrame)
print("\n'Name' and 'Occupation' columns (DataFrame):")
display(df[['Name', 'Occupation']])

# Filter rows where Age is greater than 30
print("\nPeople older than 30:")
display(df[df['Age'] > 30])

# Add a new column
df['Salary'] = [70000, 60000, 90000, 80000]
print("\nDataFrame with new 'Salary' column:")
display(df)


First 2 rows:


Name  Age         City Occupation
0  Alice   25     New York   Engineer
1    Bob   30  Los Angeles     Artist


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        4 non-null      object
 1   Age         4 non-null      int64 
 2   City        4 non-null      object
 3   Occupation  4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes

Descriptive Statistics:


Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000


'Name' column (Series):


0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


'Name' and 'Occupation' columns (DataFrame):


Name Occupation
0    Alice   Engineer
1      Bob     Artist
2  Charlie     Doctor
3    David    Manager


People older than 30:


Name  Age     City Occupation
2  Charlie   35  Chicago     Doctor
3    David   40  Houston    Manager


DataFrame with new 'Salary' column:


Name  Age         City Occupation  Salary
0    Alice   25     New York   Engineer   70000
1      Bob   30  Los Angeles     Artist   60000
2  Charlie   35      Chicago     Doctor   90000
3    David   40      Houston    Manager   80000

## NumPy Library in Python

**NumPy** (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

### Why is NumPy important?

1.  **Performance**: NumPy's core is written in C and Fortran, making it significantly faster than standard Python lists for numerical operations on large datasets.
2.  **Powerful N-dimensional Array Object (`ndarray`)**: This is the most important object in NumPy. It's a homogeneous container for data (all elements must be of the same type) and is designed for efficient storage and manipulation of numerical data.
3.  **Broadcasting**: NumPy's broadcasting feature allows operations between arrays of different shapes, simplifying code and improving performance.
4.  **Mathematical Functions**: It offers a vast collection of mathematical functions to operate on arrays, including linear algebra routines, Fourier transforms, random number generation, and more.
5.  **Foundation for Other Libraries**: Many other scientific computing libraries in Python, such as Pandas, SciPy, and Matplotlib, are built on top of NumPy.

### Core Concept: The `ndarray` Object

A NumPy `ndarray` is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the `rank` of the array; the `shape` of an array is a tuple of integers giving the size of the array along each dimension.


In [24]:
# Import the NumPy library
import numpy as np

print("NumPy library imported successfully!")

NumPy library imported successfully!


### Creating NumPy Arrays

NumPy arrays can be created in several ways:

1.  **From a Python list or tuple**
2.  **Using built-in NumPy functions** (e.g., `np.zeros`, `np.ones`, `np.arange`, `np.linspace`)
3.  **From existing data** (e.g., reading from a file)

In [25]:
# Create a 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape) # (5,) means 1 dimension with 5 elements
print("Data Type:", arr1.dtype)

# Create a 2D array (matrix) from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)
print("Shape:", arr2.shape) # (2, 3) means 2 rows, 3 columns
print("Number of dimensions (ndim):", arr2.ndim)

# Create an array of zeros
zeros_arr = np.zeros((3, 4)) # 3 rows, 4 columns
print("\nArray of Zeros:\n", zeros_arr)

# Create an array of ones
ones_arr = np.ones((2, 2))
print("\nArray of Ones:\n", ones_arr)

# Create an array with a range of values
range_arr = np.arange(0, 10, 2) # start, stop (exclusive), step
print("\nArray from arange:", range_arr)

# Create an array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5) # start, stop (inclusive), number of elements
print("\nArray from linspace:", linspace_arr)

1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data Type: int64

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions (ndim): 2

Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of Ones:
 [[1. 1.]
 [1. 1.]]

Array from arange: [0 2 4 6 8]

Array from linspace: [0.   0.25 0.5  0.75 1.  ]


### Basic Array Operations

NumPy allows for efficient element-wise operations and mathematical functions directly on arrays.

In [26]:
arr_a = np.array([10, 20, 30, 40])
arr_b = np.array([1, 2, 3, 4])

# Element-wise addition
print("Addition:", arr_a + arr_b)

# Element-wise multiplication
print("Multiplication:", arr_a * arr_b)

# Scalar multiplication
print("Scalar Multiplication:", arr_a * 2)

# Universal functions (ufuncs)
print("Square root:", np.sqrt(arr_a))
print("Sine:", np.sin(arr_b))

# Dot product (matrix multiplication)
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print("\nDot product (matrix multiplication):\n", np.dot(matrix_a, matrix_b))

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Scalar Multiplication: [20 40 60 80]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]

Dot product (matrix multiplication):
 [[19 22]
 [43 50]]


### Indexing and Slicing

NumPy arrays can be indexed and sliced much like Python lists, but with additional capabilities for multi-dimensional arrays.

In [27]:
my_matrix = np.array([[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90]])
print("Original Matrix:\n", my_matrix)

# Access a single element (row, column)
print("\nElement at [0, 1]:", my_matrix[0, 1]) # Output: 20

# Access a row
print("\nFirst row:", my_matrix[0]) # Output: [10 20 30]

# Access a column
print("\nSecond column:", my_matrix[:, 1]) # Output: [20 50 80]

# Slicing: rows 0 to 1, all columns
print("\nRows 0-1, all columns:\n", my_matrix[0:2, :])

# Slicing: all rows, columns 1 to 2
print("\nAll rows, columns 1-2:\n", my_matrix[:, 1:3])

Original Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at [0, 1]: 20

First row: [10 20 30]

Second column: [20 50 80]

Rows 0-1, all columns:
 [[10 20 30]
 [40 50 60]]

All rows, columns 1-2:
 [[20 30]
 [50 60]
 [80 90]]
